function getsonglist(){
    return [
        {
            "id": "6531",
            "songname": "夜空",
            "artist": "鈴木みのり",
            "diff": ["7","14","18","23","-1"],
            "maxdiff": 23,
            "tags": ["Anime","已完成","恋爱小行星","ED"],
            "origin": "2020年1月《恋爱小行星》ED",
            "bilisrc":"https://www.bilibili.com/video/BV1R7411Y71N",
            "time": 104,
            "bpm": [85,85],
            "note":[124,208,358,457,-1]
        },
        {
            "id": "9220",
            "songname": "One Room Sugar Life",
            "artist": "ナナヲアカリ",
            "diff": ["9","16","21","28","26"],
            "maxdiff": 28,
            "tags": ["Anime","已完成","Happy Sugar life","OP","含视频"],
            "origin": "2018年7月《Happy Sugar Life》OP",
            "bilisrc":"https://www.bilibili.com/video/BV1cE41177Ja",
            "time": 166,
            "bpm": [180,180],
            "note":[262,599,798,1314,1163],
            "video": true
        },
        {
            "id": "1235",
            "songname": "God Save The Girls",
            "artist": "下地紫野",
            "diff": ["-1","-1","-1","21","-1"],
            "maxdiff": 21,
            "tags": ["Anime","斯特拉的魔法","OP"
            ],
            "origin": "2016年10月《斯特拉的魔法》OP",
            "time": 89,
            "note":[-1,-1,-1,386,-1],
            "bpm": [170,170]
        },
        {
            "id": "4714",
            "songname": "Torchlight～夢の灯り～",
            "artist": "KiraraQuintet",
            "diff": ["-1","-1","-1","25","-1"],
            "maxdiff": 25,
            "tags": ["Game","FULL","Kirara Fantasia","OP"],
            "origin": "游戏《Kirara Fantasia》OP",
            "time": 241,
            "note":[-1,-1,-1,1211,-1],
            "bpm": [175,175]
        },
        {
            "id": "5002",
            "songname": "Jumping!!",
            "artist": "Rhodanthe※",
            "diff": ["-1","-1","17","25","-1"],
            "maxdiff": 25,
            "tags": ["Anime","黄金拼图","OP"],
            "origin": "2013年7月《黄金拼图》OP",
            "time": 89,
            "note":[-1,-1,457,555,-1],
            "bpm": [175,175]
        },
        {
            "id": "5412",
            "songname": "Foreigner Song",
            "artist": "Lioness & Nina ",
            "diff": ["-1","-1","-1","22","-1"],
            "maxdiff": 22,
            "tags": ["Anime","FULL","雏逻辑","ED"],
            "origin": "2017年7月《雏逻辑》第10话 ED",
            "time": 203,
            "note":[-1,-1,-1,769,-1],
            "bpm": [68,89]
        },
        {
            "id": "5826",
            "songname": "歩いていこう！",
            "artist": "东山奈央",
            "diff": ["-1","-1","-1","25","-1"],
            "maxdiff": 25,
            "tags": ["Anime","恋爱小行星","OP"],
            "origin": "2020年1月《恋爱小行星》OP",
            "time": 89,
            "note":[-1,-1,-1,436,-1],
            "bpm": [97,97]
        },
        {
            "id":"6225",
            "songname":"BUTTERFLY EFFECTOR",
            "artist":"TRUE",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Anime","雏逻辑","OP"],
            "origin":"2017年7月《雏逻辑》OP",
            "time":93,
            "note":[-1,-1,-1,713,-1],
            "bpm":[141,141]
        },
        {
            "id":"6933",
            "songname":"ヒロメネス",
            "artist":"Mashumairesh!!",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Anime","Show By Rock!! 活力棉花糖","OP"],
            "origin":"2020年1月《Show By Rock!! 活力棉花糖》OP",
            "time":90,
            "note":[-1,-1,-1,565,-1],
            "bpm":[120,187],
            "video":true
        },
        {
            "id":"7226",
            "songname":"カラフル·ハート·ライン",
            "artist":"桜庭遊乃 & 仁篠珠季 & 高月紗恵香",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Game","Lilycle Rainbow Stages!!","OP"],
            "origin":"游戏《Lilycle Rainbow Stages!!》OP",
            "bilisrc":"https://www.bilibili.com/video/BV1e5411W7Dm",
            "time":94,
            "note":[-1,-1,-1,674,-1],
            "bpm":[176,176]
        },
        {
            "id":"7452",
            "songname":"花雪",
            "artist":"チーム ハナヤマタ",
            "diff":["8","12","17","26","27"],
            "maxdiff":27,
            "tags":["Anime","花舞少女","ED"],
            "origin":"2014年7月《花舞少女》第12话 ED",
            "bilisrc":"https://www.bilibili.com/video/BV1X7411U7CJ",
            "time":89,
            "note":[116,218,323,557,626],
            "bpm":[146,146],
            "video":true
        },
        {
            "id":"7609",
            "songname":"ふゆびより",
            "artist":"佐々木恵梨",
            "diff":["-1","-1","-1","23","-1"],
            "maxdiff":23,
            "tags":["Anime","摇曳露营▲","ED"],
            "origin":"2018年1月《摇曳露营▲》ED",
            "bilisrc":"https://www.bilibili.com/video/BV1mk4y1q7VX",
            "time":94,
            "note":[-1,-1,-1,328,-1],
            "bpm":[110,110]
        },
        {
            "id":"7700",
            "songname":"Theme of Rabi-Ribi",
            "artist":"3R2",
            "diff":["-1","-1","-1","28","-1"],
            "maxdiff":28,
            "tags":["Game","Rabi-Ribi","OP"],
            "origin":"游戏《Rabi-Ribi》OP",
            "time":94,
            "note":[-1,-1,-1,753,-1],
            "bpm":[175,175]
        },
        {
            "id":"8083",
            "songname":"夜空",
            "artist":"鈴木みのり",
            "diff":["-1","-1","-1","24","-1"],
            "maxdiff":24,
            "tags":["Anime","恋爱小行星","ED"],
            "origin":"2020年1月《恋爱小行星》ED",
            "time":272,
            "note":[-1,-1,-1,1214,-1],
            "bpm":[85,85]
        },
        {
            "id":"8129",
            "songname":"go to romance>>>",
            "artist":"Luce Twinkle Wink☆",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Anime","Urara迷路帖","ED"],
            "origin":"2017年1月《Urara迷路帖》ED",
            "time":93,
            "note":[-1,-1,-1,585,-1],
            "bpm":[113,113]
        },
        {
            "id":"8177",
            "songname":"夢路らびりんす",
            "artist":"Labyrinth",
            "diff":["8","14","19","26","-1"],
            "maxdiff":26,
            "tags":["Anime","Urara迷路帖","OP"],
            "origin":"2017年1月《Urara迷路帖》OP",
            "bilisrc":"https://www.bilibili.com/video/BV1M7411A7am",
            "time":92,
            "note":[133,301,425,607,-1],
            "bpm":[162,162],
            "video":true
        },
        {
            "id":"8466",
            "songname":"Fragile",
            "artist":"伊藤美来&宮本侑芽",
            "diff":["-1","-1","-1","22","-1"],
            "maxdiff":22,
            "tags":["Anime","时光沙漏","OP"],
            "origin":"2019年11月《时光沙漏》OP",
            "bilisrc":"https://www.bilibili.com/video/BV1yE411G7oh",
            "time":132,
            "note":[-1,-1,-1,558,-1],
            "bpm":[84,84]
        },
        {
            "id":"9107",
            "songname":"明日への扉",
            "artist":"山田结衣&加濑友香",
            "diff":["-1","-1","-1","24","-1"],
            "maxdiff":24,
            "tags":["Anime","牵牛花与加濑同学。","ED"],
            "origin":"2018年6月《牵牛花与加濑同学。》ED",
            "time":130,
            "note":[-1,-1,-1,595,-1],
            "bpm":[100,100]
        },
        {
            "id":"9395",
            "songname":"Starfall",
            "artist":"袁娅维",
            "diff":["6","14","19","25","-1"],
            "maxdiff":25,
            "tags":["Game","崩坏3","动画短片"],
            "origin":"游戏《崩坏3》天穹流星动画短片",
            "bilisrc":"https://www.bilibili.com/video/BV1654y1D7vk",
            "time":100,
            "bpm":[76,76],
            "note":[85,263,438,499,-1],
            "video":true
        },
        {
            "id":"9654",
            "songname":"Love Emotion",
            "artist":"鈴湯",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Game","一生推不如一生恋","OP"],
            "origin":"游戏《一生推不如一生恋》OP",
            "time":77,
            "bpm":[143,143],
            "note":[-1,-1,-1,563,-1]
        },
        {
            "id":"10001",
            "songname":"よいまちカンターレ",
            "artist":"コーロまちカド",
            "diff":["-1","-1","-1","27","-1"],
            "maxdiff":27,
            "tags":["Anime","街角魔族","ED"],
            "origin":"2019年7月《街角魔族》ED",
            "time":89,
            "note":[-1,-1,-1,730,-1],
            "bpm":[171,171]
        },
        {
            "id":"10149",
            "songname":"君へと続く道",
            "artist":"相良心",
            "diff":["-1","-1","-1","24","-1"],
            "maxdiff":24,
            "tags":["Game","恋语Amrilato","OP"],
            "origin":"游戏《恋语Amrilato》OP",
            "time":87,
            "note":[-1,-1,-1,472,-1],
            "bpm":[168,168]
        },
        {
            "id":"10985",
            "songname":"キラメキFuture",
            "artist":"KiRaRe",
            "diff":["-1","-1","-1","27","-1"],
            "maxdiff":27,
            "tags":["Anime","Re:STAGE! Dream Days","插曲"],
            "origin":"2019年7月《Re:STAGE! Dream Days》第5话插曲",
            "bilisrc":"https://www.bilibili.com/video/BV1oE411G7mW",
            "time":242,
            "note":[-1,-1,-1,1756,-1],
            "bpm":[182,182]
        },
        {
            "id":"11496",
            "songname":"BanG Dream! FILM LIVE",
            "artist":"Bushiroad",
            "diff":["-1","-1","-1","-1","30"],
            "maxdiff":30,
            "tags":["Anime","BanG Dream! FILM LIVE","全文"],
            "origin":"2019年9月《BanG Dream! FILM LIVE》全文",
            //"kpsrc":"https://share.weiyun.com/5JNNCY0l",
            "time":4363,
            "bpm":[63,210],
            "note":[-1,-1,-1,-1,22468],
            "video":true
        },
        {
            "id":"11895",
            "songname":"Happy☆Pretty☆Clover",
            "artist":"Rhodanthe※",
            "diff":["-1","-1","-1","24","-1"],
            "maxdiff":24,
            "tags":["Anime","黄金拼图 Pretty Days","OP"],
            "origin":"2016年11月《黄金拼图 Pretty Days》OP",
            "bilisrc":"https://www.bilibili.com/video/BV1Q7411U7Ay",
            "time":104,
            "note":[-1,-1,-1,616,-1],
            "bpm":[182,182]
        },
        {
            "id":"12426",
            "songname":"涙はみせない",
            "artist":"こみっくがーるず",
            "diff":["-1","-1","-1","23","-1"],
            "maxdiff":23,
            "tags":["Anime","Comic Girls","ED"],
            "origin":"2018年4月《Comic Girls》ED",
            "bilisrc":"https://www.bilibili.com/video/BV1Wa4y1i7MY",
            "time":122,
            "note":[-1,-1,-1,509,-1],
            "bpm":[94,94]
        },
        {
            "id":"12824",
            "songname":"君と見た星",
            "artist":"真中 苍（CV：山口愛）",
            "diff":["-1","-1","-1","21","-1"],
            "maxdiff":21,
            "tags":["Anime","恋爱小行星","插曲"],
            "origin":"2020年1月《恋爱小行星》第9话插曲",
            "bilisrc":"https://www.bilibili.com/video/BV1az4y1d7J9",
            "time":342,
            "note":[-1,-1,-1,1165,-1],
            "bpm":[70,70]
        },
        {
            "id":"13008",
            "songname":"木もれび青春譜",
            "artist":"水濑祈，德井青空，村川梨衣",
            "diff":["-1","-1","18","-1","-1"],
            "maxdiff":18,
            "tags":["Anime","请问您今天要来点兔子吗？？~Sing For You~","插曲"],
            "origin":"2019年9月《点兔~Sing For You~》插曲",
            "bilisrc":"https://www.bilibili.com/video/BV1X7411U7jR",
            "time":90,
            "note":[-1,-1,300,-1,-1],
            "bpm":[116,116]
        },
        {
            "id":"13345",
            "songname":" あの星の向こうに",
            "artist":"高柳 知葉",
            "diff":["-1","-1","-1","20","-1"],
            "maxdiff":20,
            "tags":["Anime","恋爱小行星","ED"],
            "origin":"2020年1月《恋爱小行星》第4话ED",
            "bilisrc":"https://www.bilibili.com/video/BV1aZ4y1p79G",
            "time":123,
            "note":[-1,-1,-1,386,-1],
            "bpm":[18,72]
        },
        {
            "id":"16384",
            "songname":"永訣のGemini",
            "artist":"La priere(棗いつき/藍月なくる/nayuta)",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Other","Gemini Syndrome","单曲","自制谱比赛"],
            "origin":"2020年4月自制谱比赛第5名/B组第1",
            "bilisrc":"https://www.bilibili.com/video/BV1fV411r7Ph",
            "time":115,
            "bpm":[180,180],
            "note":[-1,-1,-1,628,-1],
        },
        {
            "id":"17046",
            "songname":"Brilliant Wings",
            "artist":"Stella Maris",
            "diff":["-1","-1","-1","28","-1"],
            "maxdiff":28,
            "tags":["Anime","Re:STAGE! Dream Days","插曲"],
            "origin":"2019年7月《Re:STAGE! Dream Days》第1话插曲",
            "bilisrc":"https://www.bilibili.com/video/BV1bC4y1W7bf",
            "time":87,
            "bpm":[200,200],
            "note":[-1,-1,-1,853,-1],
            "video":true
        },
        {
            "id":"17553",
            "songname":"Dual Ego",
            "artist":"萨顶顶",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Game","崩坏3","动画短片"],
            "origin":"游戏《崩坏3》希儿动画短片主题曲",
            "time":107,
            "bpm":[148,148],
            "note":[-1,-1,-1,498,-1]
        },
        {
            "id":"17555",
            "songname":"Kizuna Music(S02E13)",
            "artist":"Bushiroad",
            "diff":["-1","-1","-1","-1","28"],
            "maxdiff":28,
            "tags":["Anime","BanG Dream! 2nd Season","节选"],
            "origin":"2019年1月《BanG Dream! 2nd Season》13集",
            //"kpsrc":"https://share.weiyun.com/zvWGZSjt",
            "time":987,
            "bpm":[63,189],
            "note":[-1,-1,-1,-1,4735],
            "video":true
        },
        {
            "id":"18318",
            "songname":"憧れFuture Sign",
            "artist":"KiRaRe",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Anime","Re:stage Dream Days","ED"],
            "origin":"2019年7月《Re:stage Dream Days》ED",
            "time":91,
            "bpm":[181,181],
            "note":[-1,-1,-1,-507,-1],
            "video":true
        },
        {
            "id":"19015",
            "songname":"Nightglow",
            "artist":"蔡健雅",
            "diff":["-1","-1","-1","24","-1"],
            "maxdiff":24,
            "tags":["Game","崩坏3","动作短片"],
            "origin":"游戏《崩坏3》最后一课动画短片主题曲",
            "time":147,
            "bpm":[74,74],
            "note":[-1,-1,-1,625,-1],
        },
        {
            "id":"19019",
            "songname":"hectopascal",
            "artist":"寿美菜子,高田憂希",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Anime","终将成为你","ED"],
            "origin":"2018年10月《终将成为你》ED",
            "time":96,
            "bpm":[130,130],
            "note":[-1,-1,-1,659,-1],
        },
        {
            "id":"20008",
            "songname":"星と君が消えた日",
            "artist":"泠鸢yousa",
            "diff":["-1","-1","-1","24","-1"],
            "maxdiff":24,
            "tags":["Game","崩坏学院2","角色曲"],
            "origin":"游戏《崩坏学院2》德丽莎角色曲",
            "bilisrc":"https://www.bilibili.com/video/BV1nZ4y1W7UL",
            "time":98,
            "bpm":[88,88],
            "note":[-1,-1,-1,409,-1],
        },
        {
            "id":"20166",
            "songname":"Warp Destination",
            "artist":"Triodust",
            "diff":["-1","-1","-1","30","-1"],
            "maxdiff":30,
            "tags":["Game","Rabi-Ribi","BGM"],
            "origin":"游戏《Rabi-Ribi》Warp Destination地图",
            "time":99,
            "bpm":[110,110],
            "note":[-1,-1,-1,843,-1],
        },
        {
            "id":"20513",
            "songname":"Never Let You Go!",
            "artist":"七穗",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Anime","球咏","OP"],
            "origin":"2020年4月《球咏》OP",
            "time":90,
            "bpm":[156,156],
            "note":[-1,-1,-1,569,-1],
            "video":true
        },
        {
            "id":"20994",
            "songname":"璃月",
            "artist":"HOYO-MIX",
            "diff":["-1","12","-1","24","-1"],
            "maxdiff":24,
            "tags":["Game","原神","BGM"],
            "origin":"原神《汇成明霄》PV BGM",
            "bilisrc":"https://www.bilibili.com/video/BV18a4y1Y7N9",
            "time":102,
            "bpm":[112,112],
            "note":[-1,177,-1,480,-1],
        },
        {
            "id":"21447",
            "songname":"んなわけないけど",
            "artist":"ナナヲアカリ,DECO＊27",
            "diff":["-1","-1","-1","29","-1"],
            "maxdiff":29,
            "tags":["Other","ネクラロイドのあいしかた","单曲","虽然是不可能的啦"],
            "origin":"ナナヲアカリ单曲",
            "bilisrc":"https://www.bilibili.com/video/BV1fV411r7Ph",
            "time":127,
            "bpm":[208,208],
            "note":[-1,-1,-1,1114,-1],
        },
        {
            "id":"21755",
            "songname":"未来少女たち (Version 3)",
            "artist":"宇佐美奈々子,小日向縁,三ヶ月ゆい,名都借みらい",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Anime","普通女高中生要做当地偶像","ED"],
            "origin":"2014年7月《普通女高中生要做当地偶像》ED3",
            "time":109,
            "bpm":[168,168],
            "note":[-1,-1,-1,711,-1],
        },
        {
            "id":"21925",
            "songname":"シャボン -キャロver.-",
            "artist":"進藤 あまね",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Anime","百慕大三角~多彩田园曲~ ","ED"],
            "origin":"2019年1月《百慕大三角~多彩田园曲~》ED5",
            "time":90,
            "bpm":[168,168],
            "note":[-1,-1,-1,530,-1],
            "video":true
        },
        {
            "id":"22461",
            "songname":"崩坏世界的歌姬 (Movie Ver.)",
            "artist":"小林未郁",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Game","崩坏3","动作短片"],
            "origin":"游戏《崩坏3》罪人挽歌动画短片主题曲",
            "bilisrc":"https://www.bilibili.com/video/BV1wz4y1X7MD",
            "time":77,
            "bpm":[160,160],
            "note":[-1,-1,-1,367,-1],
            "video":true
        },
        {
            "id":"22550",
            "songname":"Wonderland Girl",
            "artist":"Pastel＊Palettes",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Anime","百慕大三角~多彩田园曲~ ","OP"],
            "origin":"2019年1月《百慕大三角~多彩田园曲~》OP",
            "time":272,
            "bpm":[137,137],
            "note":[-1,-1,-1,1751,-1],
        },
        {
            "id":"22847",
            "songname":"夕焼けといっしょに",
            "artist":"STARTails☆",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Anime","Slow Start","ED"],
            "origin":"2018年1月《Slow Start》第12集ED",
            "time":131,
            "bpm":[34,206],
            "note":[-1,-1,-1,707,-1],
        },
        {
            "id":"22970",
            "songname":"ユメイロコンパス",
            "artist":"高田憂希,山口愛,戸田めぐみ",
            "diff":["-1","-1","-1","23","-1"],
            "maxdiff":23,
            "tags":["Anime","New Game!!","ED"],
            "origin":"2017年7月《New Game!!》ED2",
            "time":99,
            "bpm":[130,130],
            "note":[-1,-1,-1,450,-1]
        },
        {
            "id":"23385",
            "songname":"なんとなくミライ",
            "artist":"Petit Rabbit's",
            "diff":["-1","-1","-1","24","-1"],
            "maxdiff":24,
            "tags":["Anime","请问您今天要来点兔子吗？？","ED"],
            "origin":"2015年10月《请问您今天要来点兔子吗？？》12集ED",
            "bilisrc":"https://www.bilibili.com/video/BV1ai4y1375q",
            "time":110,
            "bpm":[126,126],
            "note":[-1,-1,-1,486,-1],
        },
        {
            "id":"23614",
            "songname":"和你约定",
            "artist":"德丽莎·阿波卡利斯（CV: 花玲）",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Anime","女武神的餐桌II","ED"],
            "origin":"2020年7月《女武神的餐桌II》ED",
            "bilisrc":"https://www.bilibili.com/video/BV1dV411B7vH",
            "time":57,
            "bpm":[110,110],
            "note":[-1,-1,-1,306,-1],
            "video":true
        },
        {
            "id":"23655",
            "songname":"我的天命",
            "artist":"多多poi,宴宁",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Anime","女武神的餐桌II","OP"],
            "origin":"2020年7月《女武神的餐桌II》OP",
            "bilisrc":"https://www.bilibili.com/video/BV1a54y1q72H",
            "time":71,
            "bpm":[150,150],
            "note":[-1,-1,-1,474,-1],
        },
        {
            "id":"24182",
            "songname":"Winter",
            "artist":"3R2",
            "diff":["-1","-1","-1","25","-1"],
            "maxdiff":25,
            "tags":["Other","-","单曲",],
            "origin":"3R2单曲",
            "time":164,
            "bpm":[135,135],
            "note":[-1,-1,-1,909,-1],
        },
        {
            "id":"24454",
            "songname":"ときめきポポロン♪",
            "artist":"チマメ隊",
            "diff":["-1","-1","-1","26","-1"],
            "maxdiff":26,
            "tags":["Anime","请问您今天要来点兔子吗？？","ED"],
            "origin":"2015年10月《请问您今天要来点兔子吗？？》ED",
            "time":257,
            "bpm":[170,170],
            "note":[-1,-1,-1,1422,-1]
        }
    ]
}